name: Release
on: 
  push:
    tags:
    - '*'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - run: make
    - uses: ncipollo/release-action@v1
      with:
        artifacts: 'BUILD/pulu-*.bin'
        token: ${{ github.token }}